#!/usr/bin/env php
<?php

require_once __DIR__ . "/vendor/autoload.php";

$application = new \Symfony\Component\Console\Application;
$application->add(new \ConorSmith\GeneratorConsoleDemo\Console\MakeBaconCommand(
    new \ConorSmith\GeneratorConsoleDemo\MakeBacon(new \GuzzleHttp\Client)
));

$exitStatus = $application->run();

exit($exitStatus);
